### ISSUE TITLE
"Char Sequence is Empty" and "PNG/JPG" files.

### ISSUE THREAD

**Issue by MertDundar1** [marcodsl/FiveM-Client-Dumper#1]
JPG / PNG files are getting corrupted after dumping. And In a few servers, I'm taking "Char sequence is empty" error after fetching all manifest files. Also, your job is excellent. Thanks.

**Comment by marcodsl** [comment]
Thanks for reporting! I'm glad you liked my job.

"Char sequence is empty" error was fixed in the last release. You can download it [here](https://github.com/marcodsl/FiveM-Client-Dumper/releases).
I'm currently working on a fix for JPG / PNG file corruption. It should be available in the next few days.

**Comment by MertDundar1** [comment]
Thank you for fast reply!

**Comment by MertDundar1** [comment]
I have a suggestion. You can make a manual port selection. Because some servers don't using default port.

**Comment by marcodsl** [comment]
I just submitted a fix to the file corruption issue. You can download the patched jar file [here](https://github.com/marcodsl/FiveM-Client-Dumper/releases/tag/1.0.2). Please, don't hesitate to reopen this issue report if you find any other problem related to file corruption :)

Also, check out the [new README file](https://github.com/marcodsl/FiveM-Client-Dumper/blob/master/README.md#op%C3%A7%C3%B5es) for information about CLI options such as "port" and "output folder".

I appreciate your feedback!
